[package]
name = "bad_apple"
version = "0.0.1"
edition = "2021"

[profile.release]
#opt-level = "z"     # Optimize for size.
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = false

[dependencies]
image = "0.24.2"

